spring.application.name=Weather-App
server.port=8080

weather.api.key=7f02bfd40bdb4ef895e84521260809
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json

spring.jackson.default-property-inclusion=non_null
